# Site Settings
name: Ольга Мырсикова
email: olgamyrsikova@gmail.com
description: Sleep Consult Web Page
baseurl: ""
url: ""

# Build Settings
markdown: kramdown

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8