# Site Settings
name: Ольга Мырсикова
email: olgamyrsikova@gmail.com
description: Sleep Consult Web Page
permalink: /:title
baseurl: /sleep-consult
url: https://iriiiina.github.io

# Build Settings
markdown: kramdown

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8