# Site Settings
name: Ольга Мырсикова
email: olgamyrsikova@gmail.com
description: Sleep Consult Web Page
permalink: /:year/:month/:day/:title
baseurl: 
url: https://iriiiina.github.io/sleep-consult/

# Build Settings
markdown: kramdown

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8